### ISSUE TITLE
TFS shows 000 milliseconds for test run

### ISSUE THREAD

**Issue by creage** [no23reason/jest-trx-results-processor#245] opened 2020-07-15 17:10 UTC
I'm trying to integrate this reporter into our Playwright based tests, so we can publish test results in TFS we are hosting, but I face with time reporting issue:

![image](https://user-images.githubusercontent.com/910967/87574295-77946d00-c6ce-11ea-95a6-acfd744f0ac3.png)

`Run for 000 milliseconds` looks a bit strange.

Same test run reported by JUnit looks better:

![image](https://user-images.githubusercontent.com/910967/87574437-a579b180-c6ce-11ea-8340-b95436847b58.png)

Can we fix this issue somehow?

**Comment by no23reason** [comment] 2020-07-20 07:08
Hi, that really is strange... Do you have some outputs you can share?

**Comment by creage** [comment] 2020-07-20 07:57
@no23reason Here you go. It is a .trx file, I just renamed it to pass Github gate.

[test-results.log](https://github.com/no23reason/jest-trx-results-processor/files/4946283/test-results.log)

From what I can see, the `start` and `finish` ar the same:
```xml
<Times creation="2020-07-15T16:52:43.599Z" queuing="2020-07-15T16:52:43.599Z" start="2020-07-15T16:52:43.599Z" finish="2020-07-15T16:52:43.599Z"/>
```

**Comment by no23reason** [comment] 2022-04-12 10:45
Hi @creage can you please try the newly released version 3.0.0? It has some fixes that might be related to your issue, see #517 for the changes.

**Comment by creage** [comment] 2022-04-12 10:56
@no23reason I'm sorry, but we switched away from Jest runner, and I don't have a pipeline to test your fix on.

**Comment by no23reason** [comment] 2022-04-13 14:05
@creage no worries, thanks for replying! I will close this issue.

**Closed by no23reason** 2022-04-13 14:05 UTC
Labels: help wanted

**Comment by daiger14** [comment] 2023-03-06 10:46
Hi, the issue is still present on version 3.0.1
![image](https://user-images.githubusercontent.com/20536655/223088656-67151481-dda4-43ea-8ecb-96cb96168be5.png)
![image](https://user-images.githubusercontent.com/20536655/223088748-fd58ddb3-116b-434b-9faa-fce5cae52d9a.png)
